web/router.ex
defmodule Naranjo.Router do
  use Naranjo.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug BasicAuth, username: "naranjo", password: "secret_1x2xx"
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Naranjo do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/process", ProcessController, :new
    post "/process", ProcessController, :create
    post "/process/save", ProcessController, :history
    get "/process/:day", ProcessController, :configure
    resources "/students", StudentController
    resources "/teachers", TeacherController
    resources "/rooms", RoomController
    get "/histories", HistoryController, :index
  end

  # scope "/api", Naranjo do
  #   pipe_through :api
  # end

end

web/templates/page/index.html.eex
<div class="row" style="margin-top: 150px">

  <div class="col-lg-3 text-center">
    <%= link "HISTORIAL", to: history_path(@conn, :index), class: "btn btn-lg btn-info btn-block" %>
  </div>
  
  <div class="col-lg-3 text-center">
    <%= link "ALUMNOS", to: student_path(@conn, :index), class: "btn btn-lg btn-default btn-block" %>
  </div>

  <div class="col-lg-3 text-center">
    <%= link "PROFESORES", to: teacher_path(@conn, :index), class: "btn btn-lg btn-default btn-block" %>
  </div>

  <div class="col-lg-3 text-center">
    <%= link "SALAS", to: room_path(@conn, :index), class: "btn btn-lg btn-default btn-block" %>
  </div>
</div>
<br />
<div class="row">
  <div class="col-lg-12 text-center">
    <%= link "PROCESAR", to: process_path(@conn, :new), class: "btn btn-lg btn-primary btn-block" %>
  </div>
</div>